ALTER TABLE users
ADD COLUMN name VARCHAR(255) NOT NULL,
ADD COLUMN email VARCHAR(255) NOT NULL,
ADD COLUMN created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
ADD COLUMN updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) NOT NULL,
ADD COLUMN created_by VARCHAR(255) NOT NULL,
ADD COLUMN updated_by VARCHAR(255),
ADD CONSTRAINT unique_username UNIQUE (username);

